[project]
name = "data-swamp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "dlt[duckdb,filesystem,gs,parquet]>=1.12.1",
    "faker>=37.12.0",
    "pandas>=2.3.3",
    "polars>=1.35.1",
    "pyarrow>=21.0.0",
]
